language: cpp
install: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libxml2-dev
script:
  - git clone --depth=50 --branch=master https://github.com/ajiwo/xlfparser-c.git && cd xlfparser-c
  - rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make VERBOSE=1 && ./example/xlfsample ../example/file.xml
  - ctest -V
  - sudo make install
  - cd ../..
  - rm -rf build && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug && make VERBOSE=1 && ctest -V
  

